# Generated by Django 2.0.2 on 2019-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190205_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('extra_contacts', models.CharField(max_length=50, verbose_name='extra_contacts')),
                ('coment', models.CharField(max_length=228, verbose_name='coment')),
            ],
        ),
        migrations.DeleteModel(
            name='comentForm',
        ),
        migrations.DeleteModel(
            name='mainForm',
        ),
    ]
